version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb+srv://formula:for12345@cluster0.gze96ma.mongodb.net/?retryWrites=true&w=majority

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: