version: '3'
services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    container_name: myapp
    build: .
    ports:
      - "3003:3000"
    depends_on:
      - mongo

volumes:
  mongodb_data:
