version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Si tu archivo Dockerfile tiene un nombre diferente, ajústalo aquí.
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/database # Cambiado a "db" como host
      # Puedes agregar más variables de entorno si es necesario
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "" # Deja en blanco para no tener usuario
      MONGO_INITDB_ROOT_PASSWORD: "" # Deja en blanco para no tener contraseña
